#!/usr/bin/env bash
#Configuring Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirection_me https:\/\/github.com\/yididiabera permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
