#!/usr/bin/env bash
# This script displays "Best School" 10 times but adds "Hi" at the 9th iteration

counter="0"
while [ $counter -lt "10" ]; do
        if [ $counter -eq "3" ]; then
		echo "bad luck"
        elif [ $counter -eq "7" ]; then
                echo "good luck"
        else
		echo "Best School"
	fi
        ((counter++))
done
